// Code generated by protoc-gen-go. DO NOT EDIT.
// source: master.proto

/*
Package internal is a generated protocol buffer package.

It is generated from these files:
	master.proto
	minion.proto

It has these top-level messages:
	JoinRequest
	JoinResponse
	RuleListRequest
	RuleListResponse
	RuleRequest
	RuleResponse
	StatsRequest
	StatsResponse
*/
package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JoinRequest struct {
	Token  string              `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Minion *JoinRequest_Minion `protobuf:"bytes,2,opt,name=minion" json:"minion,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *JoinRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *JoinRequest) GetMinion() *JoinRequest_Minion {
	if m != nil {
		return m.Minion
	}
	return nil
}

type JoinRequest_Addr struct {
	Ip string `protobuf:"bytes,1,opt,name=Ip" json:"Ip,omitempty"`
}

func (m *JoinRequest_Addr) Reset()                    { *m = JoinRequest_Addr{} }
func (m *JoinRequest_Addr) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest_Addr) ProtoMessage()               {}
func (*JoinRequest_Addr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *JoinRequest_Addr) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type JoinRequest_Minion struct {
	PrivateAddrs []*JoinRequest_Addr `protobuf:"bytes,1,rep,name=PrivateAddrs" json:"PrivateAddrs,omitempty"`
	PublicAddrs  []*JoinRequest_Addr `protobuf:"bytes,2,rep,name=PublicAddrs" json:"PublicAddrs,omitempty"`
}

func (m *JoinRequest_Minion) Reset()                    { *m = JoinRequest_Minion{} }
func (m *JoinRequest_Minion) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest_Minion) ProtoMessage()               {}
func (*JoinRequest_Minion) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *JoinRequest_Minion) GetPrivateAddrs() []*JoinRequest_Addr {
	if m != nil {
		return m.PrivateAddrs
	}
	return nil
}

func (m *JoinRequest_Minion) GetPublicAddrs() []*JoinRequest_Addr {
	if m != nil {
		return m.PublicAddrs
	}
	return nil
}

type JoinResponse struct {
	Uuid    string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *JoinResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *JoinResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RuleListRequest struct {
	Uuid   string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Num    int64  `protobuf:"varint,2,opt,name=num" json:"num,omitempty"`
	Cursor string `protobuf:"bytes,3,opt,name=cursor" json:"cursor,omitempty"`
}

func (m *RuleListRequest) Reset()                    { *m = RuleListRequest{} }
func (m *RuleListRequest) String() string            { return proto.CompactTextString(m) }
func (*RuleListRequest) ProtoMessage()               {}
func (*RuleListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RuleListRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *RuleListRequest) GetNum() int64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *RuleListRequest) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type RuleListResponse struct {
	Rules  []*RuleListResponse_Rule `protobuf:"bytes,1,rep,name=Rules" json:"Rules,omitempty"`
	Cursor string                   `protobuf:"bytes,2,opt,name=Cursor" json:"Cursor,omitempty"`
}

func (m *RuleListResponse) Reset()                    { *m = RuleListResponse{} }
func (m *RuleListResponse) String() string            { return proto.CompactTextString(m) }
func (*RuleListResponse) ProtoMessage()               {}
func (*RuleListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RuleListResponse) GetRules() []*RuleListResponse_Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

func (m *RuleListResponse) GetCursor() string {
	if m != nil {
		return m.Cursor
	}
	return ""
}

type RuleListResponse_Rule struct {
}

func (m *RuleListResponse_Rule) Reset()                    { *m = RuleListResponse_Rule{} }
func (m *RuleListResponse_Rule) String() string            { return proto.CompactTextString(m) }
func (*RuleListResponse_Rule) ProtoMessage()               {}
func (*RuleListResponse_Rule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func init() {
	proto.RegisterType((*JoinRequest)(nil), "internal.JoinRequest")
	proto.RegisterType((*JoinRequest_Addr)(nil), "internal.JoinRequest.Addr")
	proto.RegisterType((*JoinRequest_Minion)(nil), "internal.JoinRequest.Minion")
	proto.RegisterType((*JoinResponse)(nil), "internal.JoinResponse")
	proto.RegisterType((*RuleListRequest)(nil), "internal.RuleListRequest")
	proto.RegisterType((*RuleListResponse)(nil), "internal.RuleListResponse")
	proto.RegisterType((*RuleListResponse_Rule)(nil), "internal.RuleListResponse.Rule")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Master service

type MasterClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	GetRuleList(ctx context.Context, in *RuleListRequest, opts ...grpc.CallOption) (*RuleListResponse, error)
}

type masterClient struct {
	cc *grpc.ClientConn
}

func NewMasterClient(cc *grpc.ClientConn) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/internal.Master/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetRuleList(ctx context.Context, in *RuleListRequest, opts ...grpc.CallOption) (*RuleListResponse, error) {
	out := new(RuleListResponse)
	err := grpc.Invoke(ctx, "/internal.Master/GetRuleList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Master service

type MasterServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	GetRuleList(context.Context, *RuleListRequest) (*RuleListResponse, error)
}

func RegisterMasterServer(s *grpc.Server, srv MasterServer) {
	s.RegisterService(&_Master_serviceDesc, srv)
}

func _Master_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Master/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetRuleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetRuleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Master/GetRuleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetRuleList(ctx, req.(*RuleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Master_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _Master_Join_Handler,
		},
		{
			MethodName: "GetRuleList",
			Handler:    _Master_GetRuleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "master.proto",
}

func init() { proto.RegisterFile("master.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xeb, 0x40,
	0x14, 0xc6, 0x9b, 0x3f, 0xcd, 0xbd, 0x3d, 0x29, 0xf7, 0x96, 0xc3, 0xbd, 0x25, 0x06, 0xc1, 0x92,
	0x55, 0x57, 0x59, 0x54, 0xc5, 0x4d, 0x11, 0x44, 0x50, 0x2a, 0x8a, 0x65, 0xde, 0x20, 0x6d, 0x07,
	0x19, 0x6c, 0x26, 0x71, 0xfe, 0xf8, 0x08, 0x82, 0xaf, 0xec, 0x4a, 0x66, 0x26, 0xa1, 0xb5, 0x44,
	0xdc, 0xcd, 0x39, 0xfc, 0xce, 0x77, 0xbe, 0xf9, 0x66, 0x60, 0x58, 0x16, 0x52, 0x51, 0x91, 0xd7,
	0xa2, 0x52, 0x15, 0xfe, 0x66, 0x5c, 0x51, 0xc1, 0x8b, 0x6d, 0xf6, 0xe1, 0x41, 0x7c, 0x57, 0x31,
	0x4e, 0xe8, 0x8b, 0xa6, 0x52, 0xe1, 0x3f, 0xe8, 0xab, 0xea, 0x99, 0xf2, 0xc4, 0x9b, 0x78, 0xd3,
	0x01, 0x71, 0x05, 0x9e, 0x41, 0x54, 0x32, 0xce, 0x2a, 0x9e, 0xf8, 0x13, 0x6f, 0x1a, 0xcf, 0x8e,
	0xf3, 0x56, 0x20, 0xdf, 0x1b, 0xce, 0x1f, 0x2c, 0x43, 0x1a, 0x36, 0x1d, 0x43, 0x78, 0xb5, 0xd9,
	0x08, 0xfc, 0x03, 0xfe, 0xa2, 0x6e, 0x04, 0xfd, 0x45, 0x9d, 0xbe, 0x79, 0x10, 0x39, 0x14, 0x2f,
	0x61, 0xb8, 0x14, 0xec, 0xb5, 0x50, 0xd4, 0x90, 0x32, 0xf1, 0x26, 0xc1, 0x34, 0x9e, 0xa5, 0xdd,
	0xf2, 0x06, 0x21, 0x5f, 0x78, 0x9c, 0x43, 0xbc, 0xd4, 0xab, 0x2d, 0x5b, 0xbb, 0x71, 0xff, 0xc7,
	0xf1, 0x7d, 0x3c, 0x9b, 0xc3, 0xd0, 0x01, 0xb2, 0xae, 0xb8, 0xa4, 0x88, 0x10, 0x6a, 0xcd, 0x36,
	0x8d, 0x55, 0x7b, 0xc6, 0x04, 0x7e, 0x95, 0x54, 0xca, 0xe2, 0x89, 0xda, 0xbb, 0x0f, 0x48, 0x5b,
	0x66, 0x8f, 0xf0, 0x97, 0xe8, 0x2d, 0xbd, 0x67, 0x52, 0xb5, 0xe9, 0x75, 0x09, 0x8c, 0x20, 0xe0,
	0xba, 0xb4, 0xc3, 0x01, 0x31, 0x47, 0x1c, 0x43, 0xb4, 0xd6, 0x42, 0x56, 0x22, 0x09, 0x2c, 0xd7,
	0x54, 0x19, 0x83, 0xd1, 0x4e, 0xb0, 0xb1, 0x74, 0x0e, 0x7d, 0xd3, 0x6b, 0x93, 0x39, 0xd9, 0x5d,
	0xed, 0x10, 0xb5, 0x0d, 0xe2, 0x68, 0xb3, 0xe2, 0xda, 0xad, 0x70, 0xa6, 0x9b, 0x2a, 0x8d, 0x20,
	0x34, 0xc0, 0xec, 0xdd, 0x3c, 0x81, 0xfd, 0x11, 0x78, 0x01, 0xa1, 0x09, 0x01, 0xff, 0x77, 0xa6,
	0x96, 0x8e, 0x0f, 0xdb, 0x6e, 0x5b, 0xd6, 0xc3, 0x1b, 0x88, 0x6f, 0xa9, 0x6a, 0x6d, 0xe0, 0x51,
	0x97, 0x35, 0xa7, 0x91, 0x7e, 0xef, 0x3a, 0xeb, 0xad, 0x22, 0xfb, 0x27, 0x4f, 0x3f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xfb, 0x0f, 0xd2, 0xed, 0xa3, 0x02, 0x00, 0x00,
}
