// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minion.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RuleRequest struct {
	Extra *google_protobuf.Struct `protobuf:"bytes,1,opt,name=extra" json:"extra,omitempty"`
}

func (m *RuleRequest) Reset()                    { *m = RuleRequest{} }
func (m *RuleRequest) String() string            { return proto.CompactTextString(m) }
func (*RuleRequest) ProtoMessage()               {}
func (*RuleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RuleRequest) GetExtra() *google_protobuf.Struct {
	if m != nil {
		return m.Extra
	}
	return nil
}

type RuleResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *RuleResponse) Reset()                    { *m = RuleResponse{} }
func (m *RuleResponse) String() string            { return proto.CompactTextString(m) }
func (*RuleResponse) ProtoMessage()               {}
func (*RuleResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RuleResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StatsRequest struct {
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type StatsResponse struct {
	Message   string                   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Processes []*StatsResponse_Process `protobuf:"bytes,2,rep,name=processes" json:"processes,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *StatsResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *StatsResponse) GetProcesses() []*StatsResponse_Process {
	if m != nil {
		return m.Processes
	}
	return nil
}

type StatsResponse_Process struct {
	Ip          string `protobuf:"bytes,1,opt,name=Ip" json:"Ip,omitempty"`
	Port        int64  `protobuf:"varint,2,opt,name=Port" json:"Port,omitempty"`
	State       string `protobuf:"bytes,3,opt,name=State" json:"State,omitempty"`
	ProcessName string `protobuf:"bytes,4,opt,name=ProcessName" json:"ProcessName,omitempty"`
	User        string `protobuf:"bytes,5,opt,name=User" json:"User,omitempty"`
	Pid         string `protobuf:"bytes,6,opt,name=Pid" json:"Pid,omitempty"`
	Proto       string `protobuf:"bytes,7,opt,name=Proto" json:"Proto,omitempty"`
}

func (m *StatsResponse_Process) Reset()                    { *m = StatsResponse_Process{} }
func (m *StatsResponse_Process) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse_Process) ProtoMessage()               {}
func (*StatsResponse_Process) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3, 0} }

func (m *StatsResponse_Process) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *StatsResponse_Process) GetPort() int64 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *StatsResponse_Process) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *StatsResponse_Process) GetProcessName() string {
	if m != nil {
		return m.ProcessName
	}
	return ""
}

func (m *StatsResponse_Process) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *StatsResponse_Process) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *StatsResponse_Process) GetProto() string {
	if m != nil {
		return m.Proto
	}
	return ""
}

func init() {
	proto.RegisterType((*RuleRequest)(nil), "internal.RuleRequest")
	proto.RegisterType((*RuleResponse)(nil), "internal.RuleResponse")
	proto.RegisterType((*StatsRequest)(nil), "internal.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "internal.StatsResponse")
	proto.RegisterType((*StatsResponse_Process)(nil), "internal.StatsResponse.Process")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Minion service

type MinionClient interface {
	PassRule(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type minionClient struct {
	cc *grpc.ClientConn
}

func NewMinionClient(cc *grpc.ClientConn) MinionClient {
	return &minionClient{cc}
}

func (c *minionClient) PassRule(ctx context.Context, in *RuleRequest, opts ...grpc.CallOption) (*RuleResponse, error) {
	out := new(RuleResponse)
	err := grpc.Invoke(ctx, "/internal.Minion/PassRule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minionClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := grpc.Invoke(ctx, "/internal.Minion/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Minion service

type MinionServer interface {
	PassRule(context.Context, *RuleRequest) (*RuleResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
}

func RegisterMinionServer(s *grpc.Server, srv MinionServer) {
	s.RegisterService(&_Minion_serviceDesc, srv)
}

func _Minion_PassRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).PassRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Minion/PassRule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).PassRule(ctx, req.(*RuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Minion_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinionServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internal.Minion/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinionServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Minion_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internal.Minion",
	HandlerType: (*MinionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PassRule",
			Handler:    _Minion_PassRule_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Minion_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minion.proto",
}

func init() { proto.RegisterFile("minion.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0x69, 0x0b, 0x05, 0xa6, 0xfc, 0xc9, 0x3f, 0x13, 0x85, 0x0d, 0x31, 0xb1, 0xe9, 0xc1,
	0x70, 0xb1, 0x24, 0x78, 0x54, 0xce, 0x86, 0x83, 0xa6, 0x29, 0xf1, 0x01, 0x0a, 0x8e, 0xa4, 0x09,
	0x74, 0x6b, 0x67, 0x9b, 0xf8, 0x00, 0x1e, 0x7d, 0x09, 0xdf, 0xd4, 0x74, 0x77, 0x09, 0xa8, 0xf1,
	0x36, 0xf3, 0xed, 0xfc, 0xbe, 0xcd, 0x7c, 0x03, 0x83, 0x7d, 0x5e, 0xe4, 0xb2, 0x88, 0xcb, 0x4a,
	0x2a, 0x89, 0xbd, 0xbc, 0x50, 0x54, 0x15, 0xd9, 0x6e, 0x72, 0xb1, 0x95, 0x72, 0xbb, 0xa3, 0x99,
	0xd6, 0xd7, 0xf5, 0xcb, 0x8c, 0x55, 0x55, 0x6f, 0x94, 0x99, 0x8b, 0xee, 0x20, 0x48, 0xeb, 0x1d,
	0xa5, 0xf4, 0x5a, 0x13, 0x2b, 0xbc, 0x86, 0x0e, 0xbd, 0xa9, 0x2a, 0x13, 0x4e, 0xe8, 0x4c, 0x83,
	0xf9, 0x38, 0x36, 0x70, 0x7c, 0x80, 0xe3, 0x95, 0x86, 0x53, 0x33, 0x15, 0x5d, 0xc1, 0xc0, 0xd0,
	0x5c, 0xca, 0x82, 0x09, 0x47, 0xe0, 0xb3, 0xca, 0x54, 0xcd, 0x9a, 0xef, 0xa7, 0xb6, 0x8b, 0x86,
	0x30, 0x58, 0xa9, 0x4c, 0xb1, 0xfd, 0x26, 0xfa, 0x70, 0xe1, 0x9f, 0x15, 0x2c, 0x29, 0xa0, 0xbb,
	0x27, 0xe6, 0x6c, 0x4b, 0x16, 0x3d, 0xb4, 0xb8, 0x80, 0x7e, 0x59, 0xc9, 0x0d, 0x31, 0x13, 0x0b,
	0x37, 0xf4, 0xa6, 0xc1, 0xfc, 0x32, 0x3e, 0x6c, 0x17, 0x7f, 0x73, 0x89, 0x13, 0x33, 0x98, 0x1e,
	0x89, 0xc9, 0xa7, 0x03, 0x5d, 0x2b, 0xe3, 0x10, 0xdc, 0x65, 0x69, 0xfd, 0xdd, 0x65, 0x89, 0x08,
	0xed, 0x44, 0x56, 0x4a, 0xb8, 0xa1, 0x33, 0xf5, 0x52, 0x5d, 0xe3, 0x19, 0x74, 0x1a, 0x4f, 0x12,
	0x9e, 0x1e, 0x33, 0x0d, 0x86, 0x10, 0x58, 0x93, 0xc7, 0x6c, 0x4f, 0xa2, 0xad, 0xdf, 0x4e, 0xa5,
	0xc6, 0xeb, 0x89, 0xa9, 0x12, 0x1d, 0xfd, 0xa4, 0x6b, 0xfc, 0x0f, 0x5e, 0x92, 0x3f, 0x0b, 0x5f,
	0x4b, 0x4d, 0xd9, 0xb8, 0x27, 0x4d, 0x94, 0xa2, 0x6b, 0xdc, 0x75, 0x33, 0x7f, 0x77, 0xc0, 0x7f,
	0xd0, 0xd7, 0xc3, 0x5b, 0xe8, 0x25, 0x19, 0x73, 0x93, 0x2a, 0x9e, 0x1f, 0xd7, 0x3c, 0xb9, 0xd1,
	0x64, 0xf4, 0x53, 0x36, 0xcb, 0x47, 0x2d, 0x5c, 0x40, 0xef, 0x9e, 0x94, 0x8e, 0x04, 0x47, 0xbf,
	0x32, 0x32, 0xf4, 0xf8, 0x8f, 0xec, 0xa2, 0xd6, 0xda, 0xd7, 0x57, 0xbe, 0xf9, 0x0a, 0x00, 0x00,
	0xff, 0xff, 0x60, 0x26, 0x00, 0x1a, 0x4a, 0x02, 0x00, 0x00,
}
